name: Daily TikTok Stats
on:
  schedule:
    - cron: '0 0 * * *'  # Runs once a day at midnight
  workflow_dispatch:      # Allows you to run it manually via the 'Actions' tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests pandas
      - name: Run tracker
        run: python tracker.py
      - name: Commit data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add tiktok_daily_stats.csv
          git commit -m "Daily update: $(date +'%Y-%m-%d')" || exit 0
          git push
